### ISSUE TITLE
Improve vectorsToAdjacency() Performance

### ISSUE THREAD

**Issue by ben-albrecht** [buddha314/numsuch#16]
Improving performance of [`vectorsToAdjacency`](https://github.com/buddha314/numsuch/blob/mad/src/gbssl.chpl#L242-L268).

- [x] Can we get a reference version to compare against?
  - [Python](https://github.com/buddha314/numsuch/blob/mad/test/reference/cosim_reference.py)

## Optimizations
- [x] Compile with optimizations (`--fast`)
   - Not in `Makefile` currently
- [x] Pre-compute and cache `dot(V[i, ..], V[i, ..])` for all `i` into an array to reduce repeated computations.
- [x] Use `1..V.size` or `V.domain` instead of `1..V.shape[1]`
   - Probably a small impact, but `size` is a *field* while `shape` is a parentheses-less *method*.
- [x] Parallelize! This computation appears to be *embarrassingly parallel*.
    - We should attempt to match serial performance with a reference version before parallelizing in order to get the best performance.

## Timings

- **dataset**: `webkb_vectors.mtx`
  - **rows:** 2740
  - **nnz:** 56985

### Local measurements

| optimization | timing (seconds) |
|---|---|
| `--fast` | `210.583`   | 
| `V.domain.dim(1)` instead of `V.shape` | `195.144` |
| Cache `dot(..)` | `110.5` |
| Remove `writeln()` per iteration | `103.134` |
| Parallelize | `†` |

*Note: each optimization builds on top of the previous one.*

† No significant impact locally (likely b/c `dot()` with MKL is already multithreaded) - this performance delta is highly dependent on hardware available.

**Comment by buddha314** [comment]
1. What does `--fast` do? I thought that just sped up the compiler, does it optimize code?
2. Yeah, that's one of the things I didn't do on purpose, but good catch.
3. Is there a typo on the `1..V.size` line?

Is there a clever use of `forall` or `coforall` in here?

**Comment by ben-albrecht** [comment]
> 1. What does --fast do? ... does it optimize code?

Yes, `--fast` should be used for any code where performance matters. See [Performance.md](https://github.com/chapel-lang/chapel/blob/master/PERFORMANCE.md#use-the---fast-flag) for more info.

> 3. Is there a typo on the 1..V.size line?

Corrected!

**Comment by buddha314** [comment]
Okay, I'll start on a naive Python version now, was trying to put that off.

**Comment by buddha314** [comment]
For reference, the original Chapel implementation without `--fast` on my laptop took 4.9 hours.  Running an equally naive Python version now.

**Comment by buddha314** [comment]
Chapel version on my laptop with the WebKB dataset:

```
./cos
Running cosine distance on W with itself.  W = (2740,56985)
  ..done in 250.368 s
```

Holy cow, nice job, Ben!  Down from 17640 so about 1.4% of the original times!

**Comment by buddha314** [comment]
Last comment, let the Python version run all night (> 8 hours) and it didn't complete.  Killed.  I'm sure scikit's implementation is faster and maybe I'll test it some day.
