### ISSUE TITLE
Index out of bounds in cosineDistance

### ISSUE THREAD

**Issue by buddha314** [buddha314/numsuch#20]
Weird this didn't show up before, but I think it's because it's taking the domain to be dynamic.  In the first line, X comes in with domain `{0..4, 0..4}`  but this line seems to expect it to start at 1:  https://github.com/buddha314/numsuch/blob/master/src/core.chpl#L78 

```Running cosineDistance
cosineDistance(X,X)
Xdom {0..4, 0..4}
dot(X[0,], X[1,]
dot(X[3,], X[4,]
dot(X[3,], X[5,]
dot(X[0,], X[2,]
../src/Core.chpl:82: error: halt reached - array index out of bounds: (5)
dot(X[0,], X[3,]
dot(X[0,], X[4,]
dot(X[0,], X[5,]
make: *** [core] Error 1
```

**Comment by buddha314** [comment]
I worked around this in a way that seemed reasonable, but I'd still like @ben-albrecht 's opinion on it.  Essentially I did this:

```
    //forall i in Xdom.dim(1) {
    forall i in Xdom.dim(1).first..Xdom.dim(1).last {
      const x2 = Xii[i];
      //for j in i+1..Xdom.dim(1).size {
      for j in i+1..Ydom.dim(1).last {
```

in both functions.  I would make it a pull request, but I fixed it right in the middle of my branch for examples.

**Comment by buddha314** [comment]
Going to close this and try to optimize at a later date if need be.

**Comment by ben-albrecht** [comment]
Sorry @buddha314 - I missed this in my notifications somehow.

Another solution is to reindex everything to 1-based indices at the start of the function, e.g.

```chpl
X1 = X.reindex({1..X.size});
```
