### ISSUE TITLE
Replace "persistSparseMatrix()" with "bulkInsert"

### ISSUE THREAD

**Issue by buddha314** [buddha314/numsuch#55]
The bulk insert should be in the `MatrixOps` package and be the default for persisting sparse matrices.

**Comment by Tshimanga** [comment]
The bulk insert function is in MatrixOps already. Do you want it renamed from `bulkInsertMatrix()` back to `persistSparseMatrix()`

**Comment by buddha314** [comment]
Yes, the "bulk" version should replace the original version, we don't need a serial version.
