### ISSUE TITLE
Method to load matrices with named columns instead of feature ids

### ISSUE THREAD

**Issue by buddha314** [buddha314/numsuch#63]
Many graphs will be in the database in the form of

```
chuck  bob  7
chuck henry 9
chuck biscuits 22
chuck wagon 1
```

Right now, we require a matrix to be loaded from a table with serial ids in the "to" and "from" columns, but this could easily be handled by the database using a temporary table.

**Comment by buddha314** [comment]
It suddenly occurs to me that we may want to keep the name / ftr id mappings somewhere.  Maybe use one of my Labeled Graph.

**Comment by buddha314** [comment]
Okay, Labeled Matrix was built for labeling data in supervised Learning.  Creating a new object called `NamedMatrix`

**Comment by Tshimanga** [comment]
This can be closed!
