### ISSUE TITLE
Write comparator for BiMap

### ISSUE THREAD

**Issue by buddha314** [buddha314/numsuch#85]
We need a comparator to get the entries of a BiMap sorted by key or by value.  If forced to choose, key is more important.

BiMap is defined in `NumSuch` [here](https://github.com/buddha314/numsuch/blob/master/src/NumSuch.chpl#L60-L150) but also reproduced right now.

```chapel
 /*
  Class to hold a <string, int> bimap.  This class does NOT enforce uniqueness but
  will skip duplicate keys.
   */
  class BiMap {
    var keys: domain(string),
        ids:  [keys] int,
        idxkey: domain(int),
        idx: [idxkey] string;

    /*
    Create an empty BiMap.
    */
    proc init() {
      this.complete();
    }

    /*
      Add string key, gives it the id based on when it entered.
      :arg k string: The string <e.g. key> to add to the BiMap
     */
    proc add(k:string) {
      if !this.keys.member(k) {
        this.keys += k;
        var i = this.keys.size;
        if i == 0 then i = 1;
        this.ids[k] = i;
        this.idxkey += i;
        this.idx[i] = k;
      }
    }

    /*
    Add a key with a given ID.  Must be done in serial.  But it begs the question: Do I need
    to have the feature ids if they have to be done in serial?
     */
    proc add(k:string, v:int) {
      this.keys += k;
      this.ids[k] = v;
      this.idxkey += v;
      this.idx[v] = k;
    }

    /*
    Send in a string, get an integer back.
     */
    proc get(k:string) {
      return this.ids[k];
    }

    /*
    Put in an integer, return a string
     */
    proc get(v:int) {
      return this.idx[v];
    }

    /*
     Iterator return tuples of (key, value)
     */
    iter entries() {
      for k in this.keys {
        yield (k, this.ids[k]);
      }
    }

    /*
    How many entries?
     */
    proc size() {
      return this.keys.size;
    }

    /*
    Returns the max value for "value", assuming it's a real number
    */
    proc max() {
      return max reduce this.idxkey;
    }

    proc uni(b: BiMap) {
      this.keys += b.keys;
      this.ids += b.ids;
      this.idxkey += b.idxkey;
      this.idx += b.idx;
      return this;
    }
}
```

**Comment by buddha314** [comment]
I tried the following, but no servicio

```chapel
record BiMapKeyComparator {
  proc compare(a,b) {
    return a[1] < b[1];
  }
  proc key(a) {return a[1];}
}
```

**Comment by ben-albrecht** [comment]
What's the error you are getting?

Tuples have a default `<` operation, and which will compare the first element, if those are equal, then the second, and so on. If that's acceptable to you, you shouldn't need to define a comparator.

**Comment by ben-albrecht** [comment]
> `elsa.chpl:17: error: unresolved call 'BiMap.sorted(comparator=BiMapKeyComparator)'`

This is telling you that there is no such thing as `BiMap.sorted()`. You probably meant to do `sort(v)`. I understand now - since you're doing a sort on the `BiMap` type and not actually an array of tuples (how I originally interpreted the question), you'll need to define a comparator which does the behavior I described above, i.e. check the first element, then the second.

**Comment by buddha314** [comment]
`sort(v, comparator=cmp);`

gives me

```
 In function 'main':
elsa.chpl:18: error: unresolved call 'sort(BiMap, comparator=BiMapKeyComparator)'
while processing the following Chapel call chain:
  elsa.chpl:18: main()
  elsa.chpl:5: chpl_gen_main(_arg: chpl_main_argument) [compiler-generated]
$CHPL_HOME/modules/packages/Sort.chpl:288: note: candidates are: sort(Data: [?Dom] ?eltType, comparator: ?rec = defaultComparator)
$CHPL_HOME/modules/packages/Sort.chpl:295: note:                 sort(Data: [?Dom] ?eltType, comparator: ?rec = defaultComparator)
```

**Comment by ben-albrecht** [comment]
Oh right, `sort` asserts that the arguments are arrays... Arguably, it should be able to sort generic types that have `this()`, `thest()`, and `<` defined, but we're not there today.

Are you able to refactor `BiMap` to actually hold an array of tuples? Otherwise, you may need to zip the arrays together into an array of tuples to hand off to the sort module, then unpack.

**Comment by daviditen** [comment]
To me it looks like you want `(key, ids)` pairs in order sorted by `key`.  If you add this iterator to your BiMap class you'll be able to call `v.sorted()` and it will yield `(key, ids)` pairs.  You shouldn't need to sort secondarily by `ids` since `key` will be unique.

```
  iter sorted() {
    use Sort;
    for key in keys.sorted() do
      yield (key, get(key));
  }
```

```
var v = new BiMap();
v.add("a");
v.add("d");
v.add("c");
v.add("b");
for val in v.sorted() {
  writeln(val);
}
```

**Comment by buddha314** [comment]
@daviditen I don't know how many beers I owe you at this point...  F(n) bitchin.  So if I make the values unique, I could sort by them.
